import Navbar from './components/Navbar';
import './globals.css';

export const metadata = {
  title: 'Ayurmahotsava',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {/* Thin orange line below Navbar */}
        <div className="h-[0.5px] bg-orange-300 mb-4"></div>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
